language: php
php:
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

before_script:
    - composer self-update
    - travis_retry composer install

install:
   - composer install

script:
    - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
    - bash <(curl -s https://codecov.io/bash)
